//BACK_END - ACTIONS 
// export const GET_COUNTRIES = "GET_COUNTRIES";
// export const GET_COUNTRIES_ID = "GET_COUNTRIES_ID";
// export const GET_COUNTRIES_NAME = "GET_COUNTRIES_NAME";
// export const POST_ACTIVITIES = "POST_ACTIVITIES";
export const GET_ACTIVITIES = "GET_ACTIVITIES";

//PAGINATION
export const NEXT_PAGE = "NEXT_PAGE";
export const PREV_PAGE = "PREV_PAGE";

//FILTERS
export const FILTER_CONTINENT = "FILTER_CONTINENT";
export const FILTER_TOURIST_ACT = "FILTER_TOURIST_ACT";

//ORDERING
export const ORDER_ACTION = "ORDER_ACTION";

//SEARCHING
export const SAVE_SEARCH_NAME = "SAVE_SEARCH_NAME";

//CREATION
export const CREATE_ACTIVITY = "CREATE_ACTIVITY";

//SAVING COUNTRIES
export const SAVE_COUNTRIES = "SAVE_COUNTRIES";